---
sudo: false

language: go

addons:
  apt:
    packages:
      musl-tools

go:
  - 1.9

env:
  - CC=musl-gcc CXX=musl-gcc GOOS=linux GOARCH=amd64 CGO_ENABLED=1

services:
  - docker

script:
  - go vet *.go
  - go build -v -a putd.go
  - docker build -t put .

before_deploy:
  - if test -n "${TRAVIS_TAG}"; then
      docker tag put "ushi/put:${TRAVIS_TAG}";
    else
      docker tag put "ushi/put:latest";
    fi
  - docker login -u $DOCKER_USER -p $DOCKER_PASS


deploy:
  - provider: script
    skip_cleanup: true
    script: docker push "ushi/put:${TRAVIS_TAG}"
    on:
      tags: true
  - provider: script
    skip_cleanup: true
    script: docker push "ushi/put:latest"
    on:
      branch: master
